AckeeCZ/ACKategories

- ACKategories/Classes/FoundationExtensions.swift
- Example/Podfile.lock
- Example/Tests/FoundationTests.swift
- Example/Tests/StringTests.swift
Same as existing `isEmpty` extension for optional String.
> isEmpty on optional collection

- ACKategories.xcodeproj/project.pbxproj
- ACKategories/CollectionExtensions.swift
- CHANGELOG.md
- Tests/CollectionTests.swift
This PR adds `isNotEmpty` and `nonEmpty` bools for `Collection`. Why? The reason for `isNotEmpty` is, well, because `!collection.isEmpty` is not really that readable and you have to go back to write it if you forget it at first which gets me kind of annoyed sometimes. 
As for `nonEmpty`, I think it's best if I point to the source I got it from: https://www.objc.io/blog/2019/01/22/non-empty-optionals/?utm_campaign=Indie%2BiOS%2BFocus%2BWeekly&utm_medium=email&utm_source=Indie_iOS_Focus_Weekly_205
> Add additional isEmpty logic for collections.

- .travis.yml
- ACKategories-Example/Flow coordinators/AppFlowCoordinator.swift
- ACKategories-Example/Flow coordinators/ModalFlowCoordinator.swift
- ACKategories-Example/Model/ExampleItem.swift
- ACKategories-Example/Screens/Base/BaseViewController.swift
- ACKategories-Example/Screens/Modal/ModalViewController.swift
- ACKategories.xcodeproj/project.pbxproj
- ACKategories/Base/FlowCoordinator.swift
- CHANGELOG.md
- Cartfile.resolved
- Documentation/FlowCoordinators.md
- README.md
This PR tries to address the issue with interactive dismiss of iOS 13 modals (#54).
This PR is considered to be a work in progress and right now is not intended to be merged at first I'd love to discuss it with the rest of the team as it contains semantically breaking change in `FlowCoordinator.start(from viewController:)` as it now expects `rootViewController` to be already set, otherwise it will fail on an `assertion`.
> Handling iOS 13 modal presentation

- ACKategories.xcodeproj/project.pbxproj
- ACKategories.xcodeproj/xcshareddata/xcschemes/ACKategories.xcscheme
- ACKategories/UISearchBarExtensions.swift
- CHANGELOG.md
This PR uses `UISearchbar.textField` on iOS 13+. Implements #57.
> ♻️ Use native `searchTextField` for `UISearchBar.textField`

- .github/workflows/docs.yml
- CHANGELOG.md
Currently docs are generated on any push to any branch. This should be changed to only push to master.
> 🔧 Generate docs only on push to master.

- .github/workflows/checks.yml
- CHANGELOG.md
Default regex for changelog check doesn't match our changelog, so the check action always thinks that changelog is missing, update of action and regex change fixes this problem.
> Fix changelog check

- ACKategories-iOS/Base/FlowCoordinator.swift
- CHANGELOG.md
In some cases, it is necessary to wait for completion of animation of `stop` function.
I am not sure how exactly I can test this, so ideas in this regard are welcome 🙂 
I tried it out in one of our projects where this was causing an issue and it worked like a charm ✨
> ✨ Add completion block for stop function.

- ACKategories-iOS/SelfSizingTableHeaderFooterView.swift
- ACKategories-iOS/TableHeaderFooterView.swift
- ACKategories.xcodeproj/project.pbxproj
- CHANGELOG.md
Resolves: https://github.com/AckeeCZ/ACKategories/issues/91
- Deprecate TableHeaderFooterView
- Introduce SelfSizingTableHeaderFooterView which inherits from UITableViewHeaderFooterView
> Deprecate TableHeaderFooterView

- ACKategories-iOS/Base/FlowCoordinator.swift
- CHANGELOG.md
Fixes a possible problem where the `completion` block is not called because of unbalanced `group.enter()` and `group.leave()` calls
> 🐛 Fix optional `presentingController` in `stop` method

- ACKategories.podspec
- ACKategories.xcodeproj/project.pbxproj
- ACKategories.xcodeproj/xcshareddata/xcschemes/ACKategories-iOS.xcscheme
- ACKategories.xcodeproj/xcshareddata/xcschemes/ACKategoriesCore.xcscheme
- CHANGELOG.md
- Package.swift
Update iOS deployment target so Xcode 12 is not complaining about importing dependency which has unsupported deployment target.
> Update iOS deployment target

- ACKategories-iOS/GradientView.swift
- CHANGELOG.md
`GradientView` should be consider non-interactive just as `UIImageView` is, so it should have `isUserInteractionEnabled = false`.
Resolves #93.
> Disable user interaction on GradientView

- ACKategories-iOS/Base/FlowCoordinator.swift
- ACKategories-iOS/ErrorHandlers.swift
- ACKategories-iOSTests/FlowCoordinator/FlowCoordinatorTests.swift
- ACKategories.xcodeproj/project.pbxproj
- CHANGELOG.md
We have a strange crash in Bazos where `rootViewController` is deallocated before the flow is stopped. Since the `rootViewController` is implicitly unwrapped and since we have no idea how to properly reproduce the crash this is the simplest solution to our problem.
I think that we have some specific bug in Bazos and this shouldn't be necessary but right now it's the only way.
> 🐛 Make sure that rootViewController is not deallocated

- ACKategories-iOS/Base/FlowCoordinator.swift
- CHANGELOG.md
Our current implementation has a problem where dying child coordinator that was `navigationController?.delegate` passes this responsibility to its parent. But if the parent has `navigationController == rootViewController` then the delegate method will also stop the parent flow. This behavior is caused by the previous fix. 😔
Currently we are not able to resolve this issue with better fix than checking if the `navigationController != rootViewController`
> 🐛 Fix navigation controller's delegate on flow coordinator that is navigation root

- ACKategories-iOS/GradientView.swift
- CHANGELOG.md
GradientView uses CAGradientLayer, which supports only `CGColor`s.  Unfortunately, `CGColor` is not automatically updated when the user changes the interface style, so we have to update colors manually.
> ✨ GradientView - update gradient colors when user interface style changed

- ACKategories.xcodeproj/project.pbxproj
- ACKategoriesCore/IntExtensions.swift
- ACKategoriesCoreTests/IntTests.swift
- CHANGELOG.md
Add `Int` extensions, that allow safe conversion of floating types to `Int` so conversion doesn't crash.
> Safe `Double` to `Int`

- ACKategoriesCore/PropertyWrappers/UserDefault.swift
- ACKategoriesCoreTests/PropertyWrappers/UserDefaultTests.swift
- CHANGELOG.md
Adds projectedValue to `UserDefault` publisher that emits values when value is set through this wrapper.
> Add publisher for `UserDefault` wrapper

- ACKategories-iOS/Base/FlowCoordinator.swift
- CHANGELOG.md
When multiple flow coordinators manage shared navigation stack, they should be chained propertly
```
ParentFlow -> ChildFlow1 -> ChildFlow2
```
But this is not always easy to achieve, sometimes you end up with hierarchy like this
```
ParentFlow -> ChildFlow1
-> ChildFlow2
```
This property is set in `start(with navigationController)`
so it can be used later in `stop` and in `UINavigationControllerDelegate` implementation
Currently a draft as I want to test it on some projects first.
> Introduce `parentNavigationDelegate` in `FlowCoordinator`

- ACKategories-iOSTests/EdgeInsetsTests.swift
- ACKategories.xcodeproj/project.pbxproj
- ACKategoriesCore/EdgeInsetsExtensions.swift
- ACKategoriesCoreTests/EdegeInsetsTests.swift
- CHANGELOG.md
When working with `EdgeInsets` in SwiftUI, we often use same insets for all edges. Usually it can be solved by using `.padding(5)` modifier and not `.padding(EdgeInsets(...))` but once insets become a parameter or return value, working with it becomes a bit annoying, thanks to these new initializers, it will be less annoying.
Wanted to add also expressible by literal conformances, but that makes `view.padding(5)` ambiguous so not doing that.
> Add EdgeInsets helper inits

- CHANGELOG.md
- Sources/ACKategories/Combine+Concurrency.swift
When combining/migrating from Combine to Concurrency, those extensions have proven handy.
> ✨ Add new extensions for Combine+Concurrency

- .github/workflows/build.yml
- .github/workflows/docbuild.yml
- .github/workflows/tests.yml
- ACKategories.xcodeproj/project.pbxproj
- CHANGELOG.md
- Sources/ACKategories/SwiftUIExtensions/View+Frame.swift
Add `readSize` modifier that is used across our SwiftUI projects
> Add SwiftUI.View+ReadSize

- CHANGELOG.md
- Sources/ACKategories/SwiftUIExtensions/View+FrameSize.swift
Add `frame` modifier that can take `CGSize` instead of `width` and `height`
> Add View+FrameSize
