AckeeCZ/ACKategories

ACKategories/Classes/Control+Blocks.swift, Example/ACKategories.xcodeproj/project.pbxproj, Example/ACKategories/Base.lproj/Main.storyboard, Example/ACKategories/ViewController.swift, Example/Podfile, Example/Podfile.lock, Example/Tests/MemoryLeakConfiguration.swift, Example/Tests/Tests.swift
Please make very detailed check! It's going to be used on a lot of places, we cannot effort bugs here.
=> Control blocks

ACKategories/Classes/Buttons+FixedIntrinsicContentSize.swift
Fixes know UIButton issue - title edge insets are not included in intrinsic content size.
=> Add title edge insets to intrinsic content size.

ACKategories/Classes/String+Extra.swift, Example/ACKategories.xcodeproj/project.pbxproj, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Tests/StringTests.swift, README.md
=> String extensions

.travis.yml, ACKategories/Classes/Control+Blocks.swift, ACKategories/Classes/TableAndCollectionViewExtensions.swift, ACKategories/Classes/UIControlEvents.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, README.md
- UITableView and UICollectionView extensions
- UIControlEvents.touchEndEvents
- Default parameter for `UIControl.on`
- fix Travis CI
=> New extensions

ACKategories.xcodeproj/project.pbxproj, ACKategories.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ACKategories.xcodeproj/xcshareddata/xcschemes/ACKategories.xcscheme, ACKategories/Classes/String+Extra.swift, ACKategories/Classes/TableHeaderFooterView.swift, ACKategories/Classes/UIControlEvents.swift, ACKategories/Info.plist, README.md
This PR adds support for Carthage dependency manager. It should not affect CocoaPods implementation.
=> Add carthage support

ACKategories.xcodeproj/project.pbxproj, ACKategories.xcodeproj/xcshareddata/xcschemes/ACKategories.xcscheme, ACKategories/String+Extra.swift, Tests/ConditionalAssignmentTests.swift, Tests/FoundationTests.swift, Tests/StringTests.swift
Add missing tests for 
- conditional assignment
- dictionary merge operator
- `Array.remove(object:)`
- `String.isNumeric`
- `String.matchesRegex`
=> Add missing tests

ACKategories.xcodeproj/project.pbxproj, ACKategories/ArrayExtensions.swift, ACKategories/CollectionExtensions.swift, Tests/ArrayTests.swift
- add safe subscript with range argument
- move safe subscript to `Collection` protocol
- add tests for safe subscript
=> Safe range subscript

.github/PULL_REQUEST_TEMPLATE.md
Adds _added tests (if applicable)_ item to PR template checklist
=> Add tests checklist item to PR template

ACKategories/FlowCoordinator.swift
=> fixed emoji on init

ACKategories-Example/Screens/BaseViewController.swift, ACKategories-Example/Screens/Example list/ExampleListViewController.swift, ACKategories-Example/Screens/UIControl blocks/UIControlBlocksViewController.swift, ACKategories-Example/Screens/VC composition/TitleViewController.swift, ACKategories.xcodeproj/project.pbxproj, ACKategories/Base/ViewController.swift, ACKategories/Base/ViewModel.swift
=> Remove generic from Base.ViewController

ACKategories.xcodeproj/project.pbxproj, ACKategories/UIViewExtensions.swift, CHANGELOG.md, Cartfile.private, Cartfile.resolved, Tests/UIViewTests.swift
=> Force intrinsic

ACKategories/UIColorExtensions.swift, CHANGELOG.md, Tests/ColorTests.swift
=> add `hexString` closure that return hex from UIColor

ACKategories.xcodeproj/project.pbxproj, CHANGELOG.md, Package.swift
=> Add SPM manifest

ACKategories/TableAndCollectionViewExtensions.swift, CHANGELOG.md
=> Add `type` parameter with default argument to `dequeue*` methods

.gitignore, CHANGELOG.md, README.md, Tapestries/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, Tapestries/Package.resolved, Tapestries/Package.swift, Tapestries/Sources/TapestryConfig/TapestryConfig.swift
This PR adds [tapestry](https://github.com/ackeecz/tapestry) to automate future releases.
=> Adding tapestry

ACKategories-Example/Screens/UIControl blocks/UIControlBlocksViewController.swift, ACKategories/UIColorExtensions.swift, CHANGELOG.md
=> Add support for DarkMode when creating images from UIColor

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, ACKategories-Example/Flow coordinators/AppFlowCoordinator.swift, ACKategories-Example/Model/ExampleItem.swift, ACKategories-Example/Screens/MapView/MapViewController.swift, ACKategories-Example/Screens/MapView/MapViewModel.swift, ACKategories.xcodeproj/project.pbxproj, ACKategories/ReusableViewExtensions.swift, CHANGELOG.md
=> Annotation view extension

ACKategories.xcodeproj/project.pbxproj, ACKategories/UIApplicationExtensions.swift, CHANGELOG.md
=> Add `clearLaunchScreenCache()`

ACKategories/UIColorExtensions.swift, CHANGELOG.md
=> 🐛 Fix wrong transparency in `UIColor.image()`

ACKategories-iOS/UIDeviceExtensions.swift, CHANGELOG.md
Add extension for `UIDevice` which extracts device model from system.
Found on [SO](https://stackoverflow.com/a/11197770/2294228) obviously 🙄
=> ✨ Add `device.modelName` extension

ACKategoriesCore/StringExtensions.swift, CHANGELOG.md
=> Fix a typo

ACKategoriesExample/Screens/Example list/ExampleListViewController.swift, CHANGELOG.md
=> Use AnyObject keyword instead of class in protocol conformance

ACKategories-iOS/GradientView.swift, CHANGELOG.md
`GradientView`'s `frame` was not being updated correctly during a transition between different orientations. Instead of addding a sublayer, we now modify the `view`'s layer directly. More [here](https://stackoverflow.com/questions/17555986/cagradientlayer-not-resizing-nicely-tearing-on-rotation)
I have also changed to a new `Changelog` format with sections `Added, Fixed, Changed`
=> 🐛 Fix layer frame on orientation change.

ACKategoriesCore/StringExtensions.swift, CHANGELOG.md
Add more arguments to `String.localized()` to allow more options for localization.
=> Add more arguments to `String.localized()`

ACKategories.xcodeproj/project.pbxproj, ACKategoriesCore/RandomExtensions/Date+Random.swift, ACKategoriesCore/RandomExtensions/Int+Random.swift, ACKategoriesCore/RandomExtensions/Randomizable.swift, ACKategoriesCore/RandomExtensions/String+Random.swift, ACKategoriesCoreTests/Random/DateRandomTests.swift, ACKategoriesCoreTests/Random/IntRandomTests.swift, ACKategoriesCoreTests/Random/StringRandomTests.swift, CHANGELOG.md
Added random extensions that can be used in tests, but also in a more general-purpose way.
There are a lot of types missing, but so far we have been able to go with just those that I have added. It should be pretty straightforward to add additional ones if such a need arises.
=> ✨ Add random extensions.

ACKategories.xcodeproj/project.pbxproj, ACKategoriesCore/PropertyWrappers/UserDefault.swift, ACKategoriesCoreTests/PropertyWrappers/UserDefaultTests.swift, CHANGELOG.md
Easy-to-use property wrapper to work with `UserDefaults` - and supports `Codable` out of the box!
=> ✨ Add UserDefault property wrapper.

ACKategories.xcodeproj/project.pbxproj, CHANGELOG.md
=> Run SwiftLint before build if available locally

ACKategories-iOS/GradientView.swift, ACKategories.xcodeproj/project.pbxproj, ACKategoriesExample/Flow coordinators/AppFlowCoordinator.swift, ACKategoriesExample/Model/ExampleItem.swift, ACKategoriesExample/Screens/GradientView/GradientViewController.swift, CHANGELOG.md
Add possibility to configure GradientView with public properties `colors` and `axis` even after init.
=> Make gradient view configurable after init

ACKategories-iOS/Base/FlowCoordinator.swift, ACKategoriesExample/Flow coordinators/ModalFlowCoordinator.swift, CHANGELOG.md
...to enable overrides in subclasses
=> Make public functions open 

ACKategories-iOS/SelfSizingTableHeaderFooterView.swift, CHANGELOG.md
- Fix crash when the user rotates the screen
- Fix initial breaking constraints
=> 🚑 SelfSizingTableHeaderFooterView - fix `layoutSubviews` sizing logic

ACKategories.xcodeproj/project.pbxproj, ACKategoriesCore/IntExtensions.swift, ACKategoriesExample/Flow coordinators/ModalFlowCoordinator.swift, CHANGELOG.md
Carthage distribution did not contain _InExtensions_ for iOS.
=> 🔧 Fix target membership of `IntExtensions`

ACKategories-iOS/Base/FlowCoordinator.swift, ACKategories-iOS/ReusableView.swift, CHANGELOG.md
- Add option to implement custom push transition
=> ✨ FlowCoordinator - custom push transition

ACKategories-iOS/ReusableView.swift, ACKategories.xcodeproj/project.pbxproj, ACKategoriesCore/PublisherExtensions.swift, CHANGELOG.md
I had to create a new PR because new commits were not showing in the [original PR](https://github.com/AckeeCZ/ACKategories/pull/116), probably due to some Github issues.
=> Publisher extensions

ACKategories-iOS/TagListView.swift, CHANGELOG.md
=> Define Obj-C name for TagListView

ACKategories-iOS/UIView+Spacer.swift, ACKategories-iOS/UIViewController+FrontMost.swift, ACKategories-iOSTests/UIViewTests.swift, ACKategories.xcodeproj/project.pbxproj, ACKategoriesCore/Combine+Concurrency.swift
While working on new project template I've identified some code, that doesn't belong to template, but belongs here.
=> Extensions from new project template

ACKategories.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/ACKategories/BackGesture.swift
- Helper function for easier back gesture setup
- iOS only (tvOS is not supported)
=> BackGesture helper

CHANGELOG.md, Sources/ACKategories/UIDeviceExtensions.swift
- Add `isTV` and `isMac` helpers/shortcuts
=> ✨ Add isTV and isMac helpers

.github/workflows/docbuild.yml
Added GitHub Action to build ACKategories documentation and deploy it as a static website with Github Pages.
=> 📝Documentation as static website

.github/workflows/build.yml
=> 👷‍♂️ Run build workflow on main push
